### ISSUE TITLE
Support for Scala 2.13

### ISSUE THREAD

**Issue by mgibowski** [avast/datadog4s#101]
It would be good to have a version for Scala 2.13.

I prepared a branch to support this version: https://github.com/avast/datadog4s/compare/master...mgibowski:scala-2.13

Here are necessary changes:
- replace usage of `scala.collection.JavaConverters` with `scala.jdk.CollectionConverters`,
- update dependency on `http4s`, `0.20.15` -> `0.21.0-M6`.

My branch is not ready for a PR, the cross compilation is not fully set up. To be able to publish artifacts locally, I first need to publish them with the setting `scalaVersion := scala212` and then again with the setting `scalaVersion := scala213` and each time they get only published with the current scala version. I don't have much time now to fix it, but maybe the above info is useful for you.

**Comment by hanny24** [comment]
I don't think we want to update http4s dependency as we would like to stay on a "stable" version if possible. However, I think we could exclude `http4s` module from cross compilation.

**Comment by tomasherman** [comment]
I agree with hanny - is http4s module for 2.13 important for you?

**Comment by mgibowski** [comment]
> I agree with hanny - is http4s module for 2.13 important for you?

Yes, currently I use it together with http4s.

**Comment by tomasherman** [comment]
i think we can use something like this, then:

https://github.com/scala/scala-module-dependency-sample

**Comment by tomasherman** [comment]
@mgibowski #103 what do you think

**Comment by tomasherman** [comment]
please try version `0.4.0` it should be xcompiled with proper http4s version
