### ISSUE TITLE
Support for sending metrics directly to StatsD

### ISSUE THREAD

**Issue by keirlawson** [avast/datadog4s#197]
**Is your feature request related to a problem? Please describe.**
I would like to be able to send metrics directly to the datadog API as I am able to do with micrometer to simplify my application deployment.

**Describe the solution you'd like**
An alternative to the StatsD implementation that talks directly to the DD API

**Describe alternatives you've considered**
Using micrometer directly, but this involved wrapping it

**Comment by tomasherman** [comment]
Hi, thanks for reaching out. Im not really sure what you have in mind. Right now you can either use the api provided by this library or you can use raw statsd clinet...what exactly do you mean by `metrics directly to the datadog API`?

**Comment by keirlawson** [comment]
So as I understand it micrometer does aggregation on your behalf in-process (as opposed to relying on statsd for this), where as by directly using the API you provide I assume such aggregation would be my responsibility?

**Comment by tomasherman** [comment]
we are not doing any aggregations, you are correct...we are providing simply a nice scala api on top of statsd client

**Comment by tomasherman** [comment]
does this cover your use case? if so, is it ok if i close this?

**Comment by keirlawson** [comment]
Not really as I was hoping for some sort of in process aggragation, but I totally get that this would make this lib way more complex and is probably out of scope, so will close :)
