### ISSUE TITLE
UDP Support

### ISSUE THREAD

**Issue by Yomanz** [avast/datadog4s#203]
**Is your feature request related to a problem? Please describe.**
I use dogstatsd over UDP and I'm unsure how to use UDP with this library.

**Describe the solution you'd like**
Ability to specify the protocol (so UDP/TCP should be used)

**Describe alternatives you've considered**
Unsure of any good alternatives.

**Additional context**
N/A

**Comment by tomasherman** [comment]
Hi @Yomanz, sorry i somehow missed this issue. Have you tried to use it? It seems like it should work. Does it not work for you?

**Comment by tomasherman** [comment]
I just checked the code and we are using [NonBlockingStatsDClient][1] which seems to be using DatagramChannel and seems compatible with UDP

[1]: https://github.com/DataDog/java-dogstatsd-client/blob/master/src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java

**Comment by Yomanz** [comment]
> I just checked the code and we are using [NonBlockingStatsDClient](https://github.com/DataDog/java-dogstatsd-client/blob/master/src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java) which seems to be using DatagramChannel and seems compatible with UDP

I'll have another look today, I might've been an idiot

**Comment by tomasherman** [comment]
@Yomanz any progres? :)

**Comment by tomasherman** [comment]
closing, feel free to re-open if the library doesn't work for you
