### ISSUE TITLE
New Release with http4s 0.23.0-RC1

### ISSUE THREAD

**Issue by valencik** [avast/datadog4s#394]
**Is your feature request related to a problem? Please describe.**
Latest datadog4s does not work with http4s 0.23.0-RC1

datadog4s 0.30.0 depends on http4s 0.23.0-RC1

`cs resolve com.avast.cloud:datadog4s_2.13:0.30.0 | grep http4s`

```
com.avast.cloud:datadog4s-http4s_2.13:0.30.0:default
org.http4s:http4s-core_2.13:0.23.0-M1:default
```

However, support for http4s 0.23.0-RC1 has been merged: https://github.com/avast/datadog4s/pull/388

sbt flags 0.23.0-M1 and 0.23.0-RC1 as binary incompatible:

```
found version conflict(s) in library dependencies; some are suspected to be binary incompatible:

* org.http4s:http4s-core_2.13:0.23.0-RC1 (early-semver) is selected over 0.23.0-M1
    +- org.http4s:http4s-jawn_2.13:0.23.0-RC1             (depends on 0.23.0-RC1)
    +- org.http4s:http4s-blaze-core_2.13:0.23.0-RC1       (depends on 0.23.0-RC1)
    +- org.http4s:http4s-circe_2.13:0.23.0-RC1            (depends on 0.23.0-RC1)
    +- org.http4s:http4s-client_2.13:0.23.0-RC1           (depends on 0.23.0-RC1)
    +- com.avast.cloud:datadog4s-http4s_2.13:0.30.0       (depends on 0.23.0-M1)
```

**Describe the solution you'd like**
Cut a new 0.30.x release of datadog4s with http4s 0.23.0-RC1 support (already merged in)

Thanks for all your work on this library, it's been lovely to use ❤️

**Comment by tomasherman** [comment]
Hey, thanks a lot for reporting and the kind words ... release is being built ;) if it all works well it should be available within half an hour or so

**Comment by tomasherman** [comment]
but maybe i will need to make it 0.31.0 due to binary incomatibility ... lets see what mima thinks :)

**Comment by tomasherman** [comment]
https://github.com/avast/datadog4s/runs/2764489092 the job succeeded, look for `v0.30.1` in a bit when sonatype processes the release :)

**Comment by tomasherman** [comment]
(it seems like it's already processed now, happy measuring :D)
