### ISSUE TITLE
Docs website has stopped working

### ISSUE THREAD

**Issue by kittsville** [avast/datadog4s#436]
**Describe the bug**

- The Documentation in the top right of the [library's homepage](https://avast.github.io/datadog4s/) now 404s
- The [User Guide](https://avast.github.io/datadog4s/userguide.html) is missing page styling

**To Reproduce**

First bug:
1. Visit [library's homepage](https://avast.github.io/datadog4s/)
2. Click "Documentation" in top right of page

Second bug:
1. Visit [User Guide](https://avast.github.io/datadog4s/userguide.html)

**Expected behavior**

- Page links go to expected pages
- All documentation pages have styling

**Comment by tomasherman** [comment]
Thanks a lot for the report, i will take a look at it today evening or tomorrow. In the meantime, if it's causing you any pain, you can find sources in https://github.com/avast/datadog4s/tree/master/site/docs ... it's not perfect but should help you fix anything urgent

**Comment by tomasherman** [comment]
Turns out it was a small issue that happened when intellij auto-formatted markdown file :( Thanks again for reporting, it should be published in a couple of minutes

**Comment by kittsville** [comment]
Thanks 👍✨

**Comment by tomasherman** [comment]
It looks like it partly helped, but the `Documentation` (meaning api documentation) is still missing. Going to reopen this until it's fully fixed

**Comment by tomasherman** [comment]
Note to self: this is caused by unidoc, https://scalameta.org/mdoc/docs/docusaurus.html#include-scaladoc-in-site might help

**Comment by tomasherman** [comment]
it seems like a bug in SBT is causing this: https://github.com/sbt/sbt/issues/6652
