### ISSUE TITLE
Release with cats-effect 3.4.8

### ISSUE THREAD

**Issue by pjrt** [avast/datadog4s#770]
The current version (0.13.2, a year old now) uses cats-effect [3.3.4](https://github.com/avast/datadog4s/blob/v0.31.2/project/Dependencies.scala#L4). 

Can we get an updated version with cats-effect 3.4.8? The `master` branch is already updated due to scala-steward. https://github.com/avast/datadog4s/blob/master/project/Dependencies.scala#L4-L5

**Comment by tomasherman** [comment]
Hi, thanks for reaching out. I've tried to release new version but unfortunately Maven central is down. I will try again later. By the way the 0.13.2 version of datadog4s uses cats-effect2 linege, if you need to cats-effect3, you should use 0.31.x version. See [note on compatibility](https://avast.github.io/datadog4s/install.html#note-on-compatibility) for more info

**Comment by pjrt** [comment]
Oh, not sure how I missed that. I guess I read `31` and `13`. Apologies. Using 0.31.x fixes my issue.
