### ISSUE TITLE
Error in dependency names

### ISSUE THREAD

**Issue by milindpatel-kt** [avast/datadog4s#84]
**Describe the bug**
Adding `"com.avast.cloud" %% "datadog4s" % "latestVersion"` OR `"com.avast.cloud" %% "datadog4s-api" % "latestVersion"` 
throws the error 
`sbt.librarymanagement.ResolveException: unresolved dependency: com.avast.cloud#datadog4s;0.3.1: not found`

**To Reproduce**
Add `"com.avast.cloud" %% "datadog4s" % "0.3.1"` in the build.sbt

**Expected behavior**
Should ideally import the required packages

**Additional context**
scalaVersion := "2.12.8"

Currently I have to add the version number with `datadog4s` as well liek so `"com.avast.cloud" % "datadog4s-api_2.12" % "0.3.1"` for expected behavior

Also, I have to add each package manually like `datadog4s-api_2.12` or `datadog4s-statsd_2.12`. 
Simply adding `datadog4s_2.12` does not work.

**Comment by tomasherman** [comment]
hello, thanks for the report. You are correct - it seems like the parent module is not actually published.

**Comment by tomasherman** [comment]
so this turned out to be slightly more hit and miss, but it is finally fixed in `0.3.6` - give it a try ;)

**Comment by milindpatel-kt** [comment]
Hi Tomas,

Thank you for the quick response. I tried it out and it worked!

**Comment by tomasherman** [comment]
happy to help :)
